"""Guards for the PLE page prefetcher. A wrong row warms the wrong bytes and proves nothing."""
import json
import os
import struct
import tempfile
import unittest
from pathlib import Path

from kv_rosetta import ple_prefetch as pp
from kv_rosetta.ple_prefetch import (PAGE, PleConstants, PlePrefetchError, TableLocation,
                                     coalesce, pages_for_rows, residency, rows_for_sequence,
                                     rows_for_token)

# The served model's constants (Qwen3.8-Flash-Next-SAFE-Q4DENSE-HC8, read via gguf-py).
SERVED = PleConstants(
    ngram_size=3, heads_per_ngram=8,
    multipliers=(23703573157769, 20109073645365, 8052911324071),
    head_offsets=(0, 20000003, 40000026, 60000059, 80000106, 100000165, 120000228,
                  140000297, 160000374, 180000455, 200000546, 220000643, 240000744,
                  260000851, 280000964, 300001081),
    head_vocab_sizes=(20000003, 20000023, 20000033, 20000047, 20000059, 20000063,
                      20000069, 20000077, 20000081, 20000091, 20000097, 20000101,
                      20000107, 20000113, 20000117, 20000119),
    eos_token_id=248044,
)
GOLDEN = Path(__file__).with_name("ple_prefetch_golden.json")


class HashTests(unittest.TestCase):
    def test_sixteen_rows_per_token(self):
        self.assertEqual(len(rows_for_token(760, [5606, 49847], SERVED)), 16)

    def test_every_row_lands_inside_its_head(self):
        rows = rows_for_token(760, [5606, 49847], SERVED)
        for h, r in enumerate(rows):
            lo = SERVED.head_offsets[h]
            self.assertTrue(lo <= r < lo + SERVED.head_vocab_sizes[h], (h, r))

    def test_bigram_heads_ignore_the_oldest_token(self):
        # heads 0..7 hash (tok, prev1); heads 8..15 hash (tok, prev1, prev2)
        a = rows_for_token(760, [1, 49847], SERVED)
        b = rows_for_token(760, [2, 49847], SERVED)
        self.assertEqual(a[:8], b[:8])
        self.assertNotEqual(a[8:], b[8:])

    def test_missing_predecessor_reads_as_eos(self):
        self.assertEqual(rows_for_token(760, [], SERVED),
                         rows_for_token(760, [SERVED.eos_token_id, SERVED.eos_token_id], SERVED))

    def test_eos_cuts_everything_older_than_itself(self):
        # prev oldest-first: [t-2, t-1]. An EOS at t-1 makes t-2 read as EOS too.
        with_eos = rows_for_token(760, [5606, SERVED.eos_token_id], SERVED)
        all_eos = rows_for_token(760, [SERVED.eos_token_id, SERVED.eos_token_id], SERVED)
        self.assertEqual(with_eos, all_eos)

    def test_own_eos_does_not_cut_own_context(self):
        a = rows_for_token(SERVED.eos_token_id, [5606, 49847], SERVED)
        b = rows_for_token(SERVED.eos_token_id, [SERVED.eos_token_id, SERVED.eos_token_id], SERVED)
        self.assertNotEqual(a, b)

    def test_sequence_walks_predecessors_oldest_first(self):
        toks = [760, 5606, 49847, 55584]
        rows = rows_for_sequence(toks, SERVED)
        self.assertEqual(len(rows), 16 * len(toks))
        self.assertEqual(rows[48:64], rows_for_token(55584, [5606, 49847], SERVED))

    @unittest.skipUnless(GOLDEN.exists(), "golden vectors not generated")
    def test_matches_the_c_verified_reference(self):
        # Generated by running ortegaalfredo/ngram-knowledge-injector's ple_core.py (whose
        # hash is tested against llama.cpp C++ golden vectors) on the served constants.
        for case in json.loads(GOLDEN.read_text()):
            got = rows_for_token(case["tok"], case["prev"], SERVED)
            self.assertEqual(got, case["rows"], case)


class PageTests(unittest.TestCase):
    def _loc(self, tmp, n_rows=1000, bpr=90, abs_offset=100):
        return TableLocation(Path(tmp), abs_offset, n_rows, 160, 20, bpr)

    def test_a_row_straddling_a_page_boundary_needs_both_pages(self):
        loc = self._loc("/x", abs_offset=0, bpr=90)
        # row 45 spans bytes 4050..4139 -> pages 0 and 4096
        self.assertEqual(pages_for_rows([45], loc), [0, PAGE])

    def test_pages_are_unique_and_sorted(self):
        loc = self._loc("/x", abs_offset=0, bpr=90)
        self.assertEqual(pages_for_rows([2, 1, 1, 0], loc), [0])

    def test_row_outside_table_is_refused(self):
        loc = self._loc("/x", n_rows=10)
        with self.assertRaises(PlePrefetchError):
            pages_for_rows([10], loc)

    def test_adjacent_pages_coalesce_into_one_run(self):
        self.assertEqual(coalesce([0, PAGE, 2 * PAGE, 8 * PAGE]),
                         [(0, 3 * PAGE), (8 * PAGE, PAGE)])


class KernelTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)
        self.path = Path(self.tmp.name) / "table.bin"
        self.path.write_bytes(os.urandom(PAGE * 8))

    def test_advise_runs_without_error(self):
        self.assertGreaterEqual(pp.advise(self.path, [(0, PAGE), (4 * PAGE, 2 * PAGE)]), 0.0)

    def test_residency_counts_only_requested_pages(self):
        resident, total = residency(self.path, [0, PAGE, 5 * PAGE])
        self.assertEqual(total, 3)
        self.assertTrue(0 <= resident <= 3)

    def test_residency_of_nothing(self):
        self.assertEqual(residency(self.path, []), (0, 0))


def _write_gguf(path: Path, kv: dict, tensors: list[tuple[str, tuple[int, ...], int, bytes]],
                alignment: int = 32) -> dict[str, int]:
    """Minimal GGUF v3 writer for the locator test. Returns absolute offsets per tensor."""
    def s(x: str) -> bytes:
        b = x.encode(); return struct.pack("<Q", len(b)) + b
    out = bytearray(b"GGUF" + struct.pack("<I", 3) + struct.pack("<Q", len(tensors))
                    + struct.pack("<Q", len(kv)))
    for k, v in kv.items():
        out += s(k)
        if isinstance(v, str):
            out += struct.pack("<I", 8) + s(v)
        elif isinstance(v, list):
            out += struct.pack("<I", 9) + struct.pack("<I", 11) + struct.pack("<Q", len(v))
            out += b"".join(struct.pack("<Q", int(x)) for x in v)
        else:
            out += struct.pack("<I", 4) + struct.pack("<I", int(v))
    rel = 0; rels = {}
    for name, dims, ttype, data in tensors:
        out += s(name) + struct.pack("<I", len(dims)) + b"".join(struct.pack("<Q", d) for d in dims)
        out += struct.pack("<I", ttype) + struct.pack("<Q", rel)
        rels[name] = rel
        rel += (len(data) + alignment - 1) // alignment * alignment
    data_start = (len(out) + alignment - 1) // alignment * alignment
    out += b"\0" * (data_start - len(out))
    absolute = {}
    for name, dims, ttype, data in tensors:
        absolute[name] = data_start + rels[name]
        out += data + b"\0" * (((len(data) + alignment - 1) // alignment * alignment) - len(data))
    path.write_bytes(bytes(out))
    return absolute


class LocatorTests(unittest.TestCase):
    def setUp(self):
        self.tmp = tempfile.TemporaryDirectory()
        self.addCleanup(self.tmp.cleanup)

    def test_finds_the_table_in_a_later_shard(self):
        d = Path(self.tmp.name)
        s1 = d / "m-00001-of-00002.gguf"; s2 = d / "m-00002-of-00002.gguf"
        _write_gguf(s1, {"general.architecture": "qwen4exp"},
                    [("token_embd.weight", (4, 2), 0, b"\0" * 32)])
        table = b"\1" * (90 * 8)                       # 8 IQ4_NL rows of 160
        absolute = _write_gguf(s2, {"general.architecture": "qwen4exp"},
                               [("other.weight", (2, 2), 0, b"\0" * 16),
                                (pp.TABLE_TENSOR, (160, 8), 20, table)])
        loc = pp.locate_table(s1)
        self.assertEqual(loc.path, s2)
        self.assertEqual(loc.abs_offset, absolute[pp.TABLE_TENSOR])
        self.assertEqual((loc.n_rows, loc.row_dim, loc.ggml_type, loc.bytes_per_row),
                         (8, 160, 20, 90))
        self.assertEqual(s2.read_bytes()[loc.abs_offset:loc.abs_offset + 90], b"\1" * 90)

    def test_unknown_table_type_is_refused_not_guessed(self):
        d = Path(self.tmp.name); s1 = d / "m.gguf"
        _write_gguf(s1, {}, [(pp.TABLE_TENSOR, (160, 2), 12, b"\0" * 300)])  # Q4_K
        with self.assertRaises(PlePrefetchError):
            pp.locate_table(s1)

    def test_missing_table_is_refused(self):
        d = Path(self.tmp.name); s1 = d / "m.gguf"
        _write_gguf(s1, {}, [("x", (2,), 0, b"\0" * 8)])
        with self.assertRaises(PlePrefetchError):
            pp.locate_table(s1)

    def test_model_without_ple_keys_is_not_warmable(self):
        d = Path(self.tmp.name); s1 = d / "m.gguf"
        _write_gguf(s1, {"general.architecture": "qwen35moe"}, [("x", (2,), 0, b"\0" * 8)])
        self.assertFalse(pp.has_ple_table(s1))
        with self.assertRaises(PlePrefetchError):
            pp.load_constants(s1)
